import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Web3 from "web3";
import Web3Modal from "web3modal";
 import WalletConnectProvider from "@walletconnect/web3-provider";
 import detectGamestopProvider from "@gamestopnft/detect-gamestop-provider";
 const providerOptions = {
  walletconnect: {
    package: WalletConnectProvider, // required
    options: {
      infuraId: "8d4eb0dcf1204e1d9347f3db31c677fd" // required
    }
  },
 detectGamestopProvider: {
    package: detectGamestopProvider, // required
    options: {
      infuraId: "8d4eb0dcf1204e1d9347f3db31c677fd" // required
    }
  },
};
let web3modal
if (typeof window !== "undefined") {
  web3modal = new Web3Modal({
    network: "gamestop",
    cacheProvider: false,
    providerOptions,
  });
}


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Meta mask wallet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Wallet connect meta mask</h1>

        <div className={styles.grid}>
          <button
            className={styles.card}
            onClick={async () => {
              const provider = await web3modal.connect();
              const web3 = new Web3(provider);
            }}
          >
            <h2> Wallet connect &rarr;</h2>
          </button>
        </div>
      </main>
    </div>
  );
}
